[package]
name = 'rplomo'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rplomo'

[dependencies]
extendr-api = '*'
plomo = {git="ssh://git@github.com/rileyleff/plomo.git"}