# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rplomo_wrappers", use_symbols = TRUE, package_name = "rplomo")

#' @docType package
#' @usage NULL
#' @useDynLib rplomo, .registration = TRUE
NULL

#' Passes a config to a model, then runs it. 
#' @export
model_runner <- function(path_to_config, path_to_output, verbose) .Call(wrap__model_runner, path_to_config, path_to_output, verbose)


# nolint end
