# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rplomo_wrappers", use_symbols = TRUE, package_name = "rplomo")

#' @docType package
#' @usage NULL
#' @useDynLib rplomo, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' @export
add <- function(x, y) .Call(wrap__add, x, y)

#' @export
run_model <- function(model, path_to_config) .Call(wrap__run_model, model, path_to_config)


# nolint end
